services:
  - type: web
    name: laravel-api
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_NAME
        value: Laravel
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:E5u0SspKCfO8O6bTFEK4n5cZhZvVXPjymaT7LOZObUo=
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://laravel-api.onrender.com

      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: debug

      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: turntable.proxy.rlwy.net
      - key: DB_PORT
        value: 36426
      - key: DB_DATABASE
        value: railway
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: qHAGPJHvsPzVwrwoIzAPnLKiblejMxXj

      - key: SESSION_DRIVER
        value: database
      - key: SESSION_LIFETIME
        value: 120
      - key: SESSION_ENCRYPT
        value: false
      - key: SESSION_PATH
        value: /
      - key: SESSION_DOMAIN
        value: null

      - key: BROADCAST_CONNECTION
        value: log
      - key: FILESYSTEM_DISK
        value: local
      - key: QUEUE_CONNECTION
        value: database
      - key: CACHE_STORE
        value: database

      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USERNAME
        value: sprjm90@gmail.com
      - key: MAIL_PASSWORD
        value: aplikasi-password-anda
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_FROM_ADDRESS
        value: sprjm90@gmail.com
      - key: MAIL_FROM_NAME
        value: "Formulir Kontak"
